

Import('env')

lib_src = [
			'SOP_Solid_Create_Sim.C',
			'SOP_Solid_Add_Object.C',
			'SOP_Solid_Solve_Sim.C',
			'SOP_Solid_Extract_Sim.C',
			'SOP_Solid_Update_Sim.C',
			'SOP_Solid_Houdini_To_CGAL.C'
			]

#env.Append(CPPPATH = ['/opt/hfs12.5.469/toolkit/include/'])
env.Append(CPPPATH = ['/opt/hfs13.0.582/toolkit/include/'])

#env.Append(CCFLAGS=['-DVERSION=\"12.5.469\"','-D_GNU_SOURCE','-DLINUX','-DAMD64','-m64','-fPIC','-DSIZEOF_VOID_P=8','-DFBX_ENABLED=1','-DOPENCL_ENABLED=1','-DOPENVDB_ENABLED=1','-DSESI_LITTLE_ENDIAN','-DENABLE_THREADS'])
env.Append(CCFLAGS=['-DVERSION=\"13.0.582\"','-D_GNU_SOURCE','-DLINUX','-DAMD64','-m64','-fPIC','-DSIZEOF_VOID_P=8','-DFBX_ENABLED=1','-DOPENCL_ENABLED=1','-DOPENVDB_ENABLED=1','-DSESI_LITTLE_ENDIAN','-DENABLE_THREADS'])
env.Append(CCFLAGS=['-DUSE_PTHREADS','-D_REENTRANT','-D_FILE_OFFSET_BITS=64','-c','-DGCC4','-DGCC3','-Wno-deprecated','-I/opt/houdini/toolkit/include','-Wall','-W','-Wno-parentheses'])
env.Append(CCFLAGS=['-Wno-sign-compare','-Wno-reorder','-Wno-uninitialized','-Wunused','-Wno-unused-parameter','-DUT_ASSERT_LEVEL=2','-fno-strict-aliasing','-DMAKING_DSO'])
env.Append(CCFLAGS=['-Wno-attributes'])

env.Append(LIBPATH = ['/usr/X11R6/lib64','/usr/X11R6/lib'])
env.Append(LIBS = ['GLU','GL','X11','Xext','Xi','dl'])


env.Append(LIBPATH = ['../adapter'])
env.Append(LIBS = ['houdini_adapter'])

env.Append(LIBPATH = ['../utils'])
env.Append(LIBS = ['houdini_utils'])

env.Append(LIBPATH = ['../../solid/solver'])
env.Append(LIBS = ['solver'])

env.Append(LIBPATH = ['../../solid/collision'])
env.Append(LIBS = ['collision'])

env.Append(LIBPATH = ['../../solid/core'])
env.Append(LIBS = ['core'])

for file in lib_src:
	lib_target = file.rstrip('.C')
	lib = env.SharedLibrary(source = file , target = lib_target)
